&define Black                  #000000
&define Navy                   #000080
&define DarkBlue               #00008B
&define MediumBlue             #0000CD
&define Blue                   #0000FF
&define DarkGreen              #006400
&define Green                  #008000
&define Teal                   #008080
&define DarkCyan               #008B8B
&define DeepSkyBlue            #00BFFF
&define DarkTurquoise          #00CED1
&define MediumSpringGreen      #00FA9A
&define Lime                   #00FF00
&define SpringGreen            #00FF7F
&define Aqua                   #00FFFF
&define Cyan                   #00FFFF
&define MidnightBlue           #191970
&define DodgerBlue             #1E90FF
&define LightSeaGreen          #20B2AA
&define ForestGreen            #228B22
&define SeaGreen               #2E8B57
&define DarkSlateGray          #2F4F4F
&define DarkSlateGrey          #2F4F4F
&define LimeGreen              #32CD32
&define MediumSeaGreen         #3CB371
&define Turquoise              #40E0D0
&define RoyalBlue              #4169E1
&define SteelBlue              #4682B4
&define DarkSlateBlue          #483D8B
&define MediumTurquoise        #48D1CC
&define Indigo                 #4B0082
&define DarkOliveGreen         #556B2F
&define CadetBlue              #5F9EA0
&define CornflowerBlue         #6495ED
&define RebeccaPurple          #663399
&define MediumAquaMarine       #66CDAA
&define DimGray                #696969
&define DimGrey                #696969
&define SlateBlue              #6A5ACD
&define OliveDrab              #6B8E23
&define SlateGray              #708090
&define SlateGrey              #708090
&define LightSlateGray         #778899
&define LightSlateGrey         #778899
&define MediumSlateBlue        #7B68EE
&define LawnGreen              #7CFC00
&define Chartreuse             #7FFF00
&define Aquamarine             #7FFFD4
&define Maroon                 #800000
&define Purple                 #800080
&define Olive                  #808000
&define Gray                   #808080
&define Grey                   #808080
&define SkyBlue                #87CEEB
&define LightSkyBlue           #87CEFA
&define BlueViolet             #8A2BE2
&define DarkRed                #8B0000
&define DarkMagenta            #8B008B
&define SaddleBrown            #8B4513
&define DarkSeaGreen           #8FBC8F
&define LightGreen             #90EE90
&define MediumPurple           #9370DB
&define DarkViolet             #9400D3
&define PaleGreen              #98FB98
&define DarkOrchid             #9932CC
&define YellowGreen            #9ACD32
&define Sienna                 #A0522D
&define Brown                  #A52A2A
&define DarkGray               #A9A9A9
&define DarkGrey               #A9A9A9
&define LightBlue              #ADD8E6
&define GreenYellow            #ADFF2F
&define PaleTurquoise          #AFEEEE
&define LightSteelBlue         #B0C4DE
&define PowderBlue             #B0E0E6
&define FireBrick              #B22222
&define DarkGoldenRod          #B8860B
&define MediumOrchid           #BA55D3
&define RosyBrown              #BC8F8F
&define DarkKhaki              #BDB76B
&define Silver                 #C0C0C0
&define MediumVioletRed        #C71585
&define IndianRed              #CD5C5C
&define Peru                   #CD853F
&define Chocolate              #D2691E
&define Tan                    #D2B48C
&define LightGray              #D3D3D3
&define LightGrey              #D3D3D3
&define Thistle                #D8BFD8
&define Orchid                 #DA70D6
&define GoldenRod              #DAA520
&define PaleVioletRed          #DB7093
&define Crimson                #DC143C
&define Gainsboro              #DCDCDC
&define Plum                   #DDA0DD
&define BurlyWood              #DEB887
&define LightCyan              #E0FFFF
&define Lavender               #E6E6FA
&define DarkSalmon             #E9967A
&define Violet                 #EE82EE
&define PaleGoldenRod          #EEE8AA
&define LightCoral             #F08080
&define Khaki                  #F0E68C
&define AliceBlue              #F0F8FF
&define HoneyDew               #F0FFF0
&define Azure                  #F0FFFF
&define SandyBrown             #F4A460
&define Wheat                  #F5DEB3
&define Beige                  #F5F5DC
&define WhiteSmoke             #F5F5F5
&define MintCream              #F5FFFA
&define GhostWhite             #F8F8FF
&define Salmon                 #FA8072
&define AntiqueWhite           #FAEBD7
&define Linen                  #FAF0E6
&define LightGoldenRodYellow   #FAFAD2
&define OldLace                #FDF5E6
&define Red                    #FF0000
&define Fuchsia                #FF00FF
&define Magenta                #FF00FF
&define DeepPink               #FF1493
&define OrangeRed              #FF4500
&define Tomato                 #FF6347
&define HotPink                #FF69B4
&define Coral                  #FF7F50
&define DarkOrange             #FF8C00
&define LightSalmon            #FFA07A
&define Orange                 #FFA500
&define LightPink              #FFB6C1
&define Pink                   #FFC0CB
&define Gold                   #FFD700
&define PeachPuff              #FFDAB9
&define NavajoWhite            #FFDEAD
&define Moccasin               #FFE4B5
&define Bisque                 #FFE4C4
&define MistyRose              #FFE4E1
&define BlanchedAlmond         #FFEBCD
&define PapayaWhip             #FFEFD5
&define LavenderBlush          #FFF0F5
&define SeaShell               #FFF5EE
&define Cornsilk               #FFF8DC
&define LemonChiffon           #FFFACD
&define FloralWhite            #FFFAF0
&define Snow                   #FFFAFA
&define Yellow                 #FFFF00
&define LightYellow            #FFFFE0
&define Ivory                  #FFFFF0
&define White                  #FFFFFF
