#!/bin/bash

function mktest
{
    local TEST=$1
    echo -e "\n#### Test $TEST\n"

    local TEMPLATE=tests/${TEST}.jqt
    local METADATA=tests/${TEST}.json
    local EXPECTED=tests/expected/${TEST}.txt
    [[ -e $EXPECTED ]] || EXPECTED=tests/expected/${TEST}.jqt

    echo -e "\n**Template**:\n"
    echo '```'
    cat $TEMPLATE
    echo '```'
    
    if [[ -e $METADATA ]]; then
        echo -e "\n**JSON input**:\n"
        echo '```'
        cat $METADATA
        echo '```'
    fi
    
    echo -e "\n**Output generated**:\n"
    echo '```'
    cat $EXPECTED
    echo '```'
}

function mkdoc
{
    for f in tests/$1-??.jqt; do
        local TEST=${f#tests/}; TEST=${TEST%.jqt}
        [[ $TEST == *00 ]] && continue
        mktest $TEST
    done
}

exec > examples.md

cd ..

echo -e "# Tests\n"
echo -e "\n# Examples\n"

echo -e "\n### Expressions\n"
mkdoc expr
echo -e "\n### Conditionals\n"
mkdoc cond
echo -e "\n### Loops\n"
mkdoc loop

#?echo -e "\n# Bulk tests\n"
#?echo -e "\n### Syntax\n"
#?mktest 'syntax-00'
#?echo -e "\n### Expressions\n"
#?mktest 'expr-00'
#?echo -e "\n### Conditionals\n"
#?mktest 'cond-00'
#?echo -e "\n### Loops\n"
#?mktest 'loop-00'

# vim:ai:sw=4:ts=4:et:syntax=sh
