---
#
# jqt docs configuration
#
# Provide defaults to each .md file including "config.yaml" before defining
# other elements, and is available in the .site top-level variable.
#

#
# Global parameters
#

# Default values:
#
# Destination: ./_site
# Assets:      ./assets
# Blocks:      ./blocks
# Content:     ./content
# Data:        ./data
# Layouts:     ./layouts
# Styles:      ./styles

# Changes from defaults
Destination: /tmp/jqt   # fast RAM disk

#
# Site parameters
#

baseurl: https://fadado.github.io/jqt

title: jqt, the jq template engine
baseURL: https://fadado.github.com/jqt/
lang: &lang en
logo: "❴❴❏❵❵"

author: &author 
- email: jordinas@gmail.com
  name: Joan Josep Ordinas Rosa
menu:
  - index
  - engine
  - structure
  - content
  - data

# Default values
defaults:
  - idprefix: "" # all files
    properties:
      title-prefix: jqt
      author: *author
      lang: *lang

# vim:ts=2:sw=2:ai:et:fileencoding=utf8:syntax=yaml
...
