#
# jqt docs configuration
#
# Provide defaults to each .md file including "config.yaml" before defining
# other elements, and is available in the .site top-level variable.
#

# Global parameters

title: jqt · the jq template engine
baseURL: https://fadado.github.com/jqt/
lang: en

author:
- email: jordinas@gmail.com
  name: Joan Josep Ordinas Rosa

menu:
- URL: ./index.html
  id: content/home
  name: Home
- URL: ./engine.html
  id: content/engine
  name: Engine
- URL: ./template.html
  id: content/template
  name: Template
- URL: ./document.html
  id: content/document
  name: Document
- URL: ./data.html
  id: content/data
  name: Data

# vim:ts=2:sw=2:ai:et:fileencoding=utf8:syntax=yaml
