---
#
# jqt docs configuration
#
# Provide defaults to each .md file including "config.yaml" before defining
# other elements, and is available in the .site top-level variable.
#

# Global parameters

title: jqt > the jq template engine
baseURL: https://fadado.github.com/jqt/
lang: en
logo: "❴❴❏❵❵"

author:
- email: jordinas@gmail.com
  name: Joan Josep Ordinas Rosa

menu:
- URL: ./engine.html
  path: content/engine.md
  name: Engine
- URL: ./structure.html
  path: content/structure.md
  name: Structure
- URL: ./content.html
  path: content/content.md
  name: Content
- URL: ./data.html
  path: content/data.md
  name: Data

# vim:ts=2:sw=2:ai:et:fileencoding=utf8:syntax=yaml
...
