---
#
# jqt documentation site configuration
#
# Provide defaults to each MarkDown file including `config.yaml`, and is
# available in the `.site` top-level variable.
#

# ======================================================================
# Site variables with default values. Can be redefined in this file.
# ======================================================================
#
# Assets        assets
# Blocks        blocks
# Content       content
# Data          data
# Root          _site
# Layouts       layouts
# Styles        styles

# Changes from defaults (fast RAM disk)
Root: /tmp/jqt

#
# Site parameters
#

title: jqt, the jq template engine
title_prefix: jqt
title_delimiter: "·"
baseurl: https://fadado.github.com/jqt/
lang: &lang en
logo: "❴❴❏❵❵"

author: &author 
- email: jordinas@gmail.com
  name: Joan Josep Ordinas Rosa
menu:
  - index
  - engine
  - structure
  - content
  - data
# - blog/index

# Default values
defaults:
  - idprefix: "" # all files
    properties:
      author: *author
      lang: *lang
      Layout: page-toc
      Datasets:
        - snippets.md
      Dependencies:
        - content/macros.m
        - content/LINKS.txt 
#     Flags:
#       - -mXYZ:$(Meta)/XYZ.json
  - idprefix: "blog/"
    properties:
      Layout: page

# vim:ts=2:sw=2:ai:et:fileencoding=utf8:syntax=yaml
...
