---
#
# jqt documentation site configuration
#
# Provide defaults to each MarkDown file including `config.yaml`, and is
# available in the `.site` top-level variable.
#

# ======================================================================
# Site variables with default values. Can be redefined in this file.
# ======================================================================
#
# Assets        assets
# Blocks        blocks
# Content       content
# Data          data
# Destination   _site
# Layouts       layouts
# Styles        styles

# Changes from defaults (fast RAM disk)
Destination: /tmp/jqt

#
# Site parameters
#

# Site version (same as jqt)
version: 0.5.1

title: jqt, the jq template engine
baseurl: https://fadado.github.com/jqt/
lang: &lang en
logo: "❴❴❏❵❵"

author: &author 
- email: jordinas@gmail.com
  name: Joan Josep Ordinas Rosa
menu:
  - index
  - engine
  - structure
  - content
  - data
# - blog/index

# Default values
defaults:
  - idprefix: "" # all files
    properties:
      title-prefix: jqt
      author: *author
      lang: *lang
      Datasets:
        - snippets
      Dependencies:
        - layouts/default.html
        - content/macros.m
        - content/LINKS.txt 
#     Flags:
#       - -mXYZ:$(Metadata)/XYZ.json

# vim:ts=2:sw=2:ai:et:fileencoding=utf8:syntax=yaml
...
