---
#
# jqt docs configuration
#
# Provide defaults to each .md file including "config.yaml" before defining
# other elements, and is available in the .site top-level variable.
#

#
# Global parameters
#

# Default values:
#
# Destination: ./_site
# Assets:      ./assets
# Blocks:      ./blocks
# Content:     ./content
# Data:        ./data
# Layouts:     ./layouts
# Styles:      ./styles

# Changes from defaults
Destination: /tmp/jqt   # fast RAM disk
Layouts:     ./blocks   # shared space

#
# Site parameters
#

title: jqt, the jq template engine
baseURL: https://fadado.github.com/jqt/
lang: en
logo: "❴❴❏❵❵"

author:
- email: jordinas@gmail.com
  name: Joan Josep Ordinas Rosa

# TODO: instrospect
menu:
- URL: ./index.html
  path: content/index.md
  name: Home
- URL: ./engine.html
  path: content/engine.md
  name: Engine
- URL: ./structure.html
  path: content/structure.md
  name: Structure
- URL: ./content.html
  path: content/content.md
  name: Content
- URL: ./data.html
  path: content/data.md
  name: Data

# vim:ts=2:sw=2:ai:et:fileencoding=utf8:syntax=yaml
...
